### ISSUE TITLE
request endpoint was not found

### ISSUE THREAD

**Issue by Mia-Zhang-Forever** [ahonn/keygen-rs#2]
<img width="797" alt="image" src="https://github.com/user-attachments/assets/960c45d3-dee1-4665-b22f-4e2331b1beb9">

This is what from the example:

I set the api_url to:    ` let api_url = "https://api.keygen.sh/v1".to_string();`

**Comment by ezekg** [comment]
The `api_url` should not include [the version prefix](https://github.com/ahonn/keygen-rs/blob/master/src/config.rs#L26). It's [appended automatically](https://github.com/ahonn/keygen-rs/blob/master/src/client.rs#L162-L176).
